
name: Terraform deploy to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a terraform init
    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
    with:
    tf_actions_version: 0.12.13
    tf_actions_subcommand: "init"

    # Runs a terraform plan
    - name: "Terraform Plan"
     uses: hashicorp/terraform-github-actions@master
    with:
    tf_actions_version: 0.12.13
    tf_actions_subcommand: "plan"
    args: '-var="client_secret=${{ secrets.client_Secret }}"'
   - name: "Terraform Apply"
    uses: hashicorp/terraform-github-actions@master
    with:
    tf_actions_version: 0.12.13
    tf_actions_subcommand: "apply"
    args: '-var="client_secret=${{ secrets.client_Secret }}"'
